In [2]:
import numpy as np

In [3]:
num_states = 16
dim = 4

def create_feature(num_states, dim):
    feature = np.zeros((num_states, dim))
    for i in range(num_states):
        if i in [0,1,4,5]:
            feature[i] = np.array([1,0,0,0])
        elif i in [2,3,6,7]:
            feature[i] = np.array([0,1,0,0])
        elif i in [8,9,12,13]:
            feature[i] = np.array([0,0,1,0])
        else:
            feature[i] = np.array([0,0,0,1])
    return feature

feature = create_feature(num_states, dim)
print(feature)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
